'use client';
import {useEffect,useMemo,useState} from 'react';
import products from '@/data/products';

const money=n=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(n);
const sizes=[{g:250,label:'250 g',mult:1},{g:1000,label:'1 kg',mult:4},{g:3000,label:'3 × 1 kg',mult:12}];
const voucherCode=value=>`REZERVACE${Math.round(value/100)*100}`;

export default function ClubApp(){
 const [view,setView]=useState('home'); const [selected,setSelected]=useState(products[0]); const [size,setSize]=useState(sizes[1]);
 const [user,setUser]=useState(null); const [authOpen,setAuthOpen]=useState(false); const [reserveOpen,setReserveOpen]=useState(false); const [reservations,setReservations]=useState([]); const [toast,setToast]=useState('');
 useEffect(()=>{try{setUser(JSON.parse(localStorage.getItem('bb-user')));setReservations(JSON.parse(localStorage.getItem('bb-reservations'))||[])}catch{}},[]);
 const retail=selected.price250*size.mult, presale=Math.round(retail*.85);
 function go(v){setView(v);window.scrollTo({top:0,behavior:'smooth'})}
 function choose(p){setSelected(p);setSize(sizes[1]);setView('detail');window.scrollTo(0,0)}
 function startReserve(){if(!user){setAuthOpen(true);return}setReserveOpen(true)}
 function finishReserve(delivery){const item={id:Date.now(),product:selected.name,size:size.label,paid:presale,value:retail,code:voucherCode(retail),delivery,status:'Rezervace potvrzena'};const next=[item,...reservations];setReservations(next);localStorage.setItem('bb-reservations',JSON.stringify(next));setReserveOpen(false);setToast('Rezervace byla úspěšně vytvořena.');setView('account');setTimeout(()=>setToast(''),3200)}
 function logout(){setUser(null);localStorage.removeItem('bb-user');go('home')}
 return <div className="app">
  <Header view={view} go={go} user={user} setAuthOpen={setAuthOpen}/>
  {view==='home'&&<Home choose={choose} go={go}/>} {view==='campaigns'&&<Campaigns choose={choose}/>} {view==='detail'&&<Detail p={selected} size={size} setSize={setSize} retail={retail} presale={presale} startReserve={startReserve} go={go}/>} {view==='account'&&<Account user={user} reservations={reservations} setAuthOpen={setAuthOpen} logout={logout}/>} {view==='behind'&&<Behind/>}
  <Footer go={go}/>{authOpen&&<AuthModal onClose={()=>setAuthOpen(false)} onLogin={u=>{setUser(u);localStorage.setItem('bb-user',JSON.stringify(u));setAuthOpen(false);setToast('Jste přihlášeni.')}}/>}{reserveOpen&&<ReserveModal p={selected} size={size} retail={retail} presale={presale} onClose={()=>setReserveOpen(false)} finish={finishReserve}/>} {toast&&<div className="toast">✓ {toast}</div>}
 </div>
}
function Header({view,go,user,setAuthOpen}){return <header><button className="brand" onClick={()=>go('home')}><span>BB</span><div><b>BioBezObalu</b><small>CHOCOLATE CLUB</small></div></button><nav><button className={view==='home'?'on':''} onClick={()=>go('home')}>Domů</button><button className={view==='campaigns'||view==='detail'?'on':''} onClick={()=>go('campaigns')}>Předprodeje</button><button className={view==='behind'?'on':''} onClick={()=>go('behind')}>Ze zákulisí</button></nav><div className="header-actions"><a href="https://biobezobalu.cz" target="_blank">E-shop ↗</a><button className="account-btn" onClick={()=>user?go('account'):setAuthOpen(true)}>{user?user.name.split(' ')[0]:'Přihlásit se'}</button></div></header>}
function Home({choose,go}){return <main><section className="hero"><div className="hero-copy"><div className="eyebrow">LIMITOVANÉ ČOKOLÁDY • SLEVA 15 %</div><h1>Rozhodněte, co vyrobíme příště.</h1><p>Rezervujte čokoládu během kampaně, zaplaťte o 15 % méně a sledujte její cestu od nápadu až po výrobu.</p><div className="hero-buttons"><button className="primary" onClick={()=>go('campaigns')}>Prohlédnout předprodeje</button><button className="ghost" onClick={()=>document.getElementById('how').scrollIntoView({behavior:'smooth'})}>Jak to funguje</button></div><div className="trust"><span>↩ Kdykoliv zrušíte</span><span>⚡ Peníze obratem zpět</span><span>🌱 Všechny kampaně vegan</span></div></div><div className="hero-card"><img src="/chocolate-1.jpg"/><div className="float-badge">68 % rezervováno</div><div className="hero-card-info"><small>NEJBLÍŽE K VÝROBĚ</small><h3>Malina 70 %</h3><div className="bar"><i style={{width:'68%'}}/></div><div><b>68 kg z 100 kg</b><span>Zbývá 12 dní</span></div></div></div></section>
<section id="how" className="how"><div className="section-head"><span>JAK TO FUNGUJE</span><h2>Jednodušší než běžná předobjednávka</h2><p>Platíte rovnou zvýhodněnou cenu. O zbytek se postaráme my.</p></div><div className="steps"><Step n="01" t="Vyberete čokoládu" x="Zvolíte příchuť a množství, které chcete rezervovat."/><Step n="02" t="Zaplatíte o 15 % méně" x="Celou zvýhodněnou cenu uhradíte bezpečně v aplikaci."/><Step n="03" t="Sledujete výrobu" x="V účtu vidíte stav kampaně i postup výroby vaší várky."/><Step n="04" t="Vyzvednete přes e-shop" x="Po výrobě dostanete voucher v plné hodnotě produktu."/></div><div className="how-note"><b>Rezervace bez rizika.</b><span>Můžete ji zrušit během kampaně i kdykoliv potom. Zaplacenou částku vám obratem vrátíme.</span></div></section>
<section className="featured"><div className="section-head row"><div><span>AKTIVNÍ PŘEDPRODEJE</span><h2>Pomozte rozhodnout o další várce</h2></div><button className="text-btn" onClick={()=>go('campaigns')}>Zobrazit všechny →</button></div><div className="cards">{products.slice(0,3).map(p=><ProductCard key={p.slug} p={p} choose={choose}/>)}</div></section>
<section className="voucher-explain"><div><span className="eyebrow">VOUCHER PO VÝROBĚ</span><h2>Rezervace vám neubere výhody z e-shopu.</h2><p>Čokoládu po výrobě vložíte do košíku za běžnou cenu a uplatníte voucher v její plné hodnotě. Díky tomu se produkt započítá do limitu pro dopravu zdarma i do objemových slev na e-shopu.</p></div><div className="voucher-card"><small>VAŠE REZERVACE</small><h3>Malina 70 % • 1 kg</h3><div className="price-line"><span>Zaplaceno v předprodeji</span><b>983 Kč</b></div><div className="code"><span>REZERVACE1200</span><button>Kopírovat</button></div><small>Hodnota voucheru 1 156 Kč</small></div></section></main>}
function Step({n,t,x}){return <article className="step"><b>{n}</b><div><h3>{t}</h3><p>{x}</p></div></article>}
function ProductCard({p,choose}){return <article className="product-card" onClick={()=>choose(p)}><div className="product-img"><img src={p.image}/><span className="vegan">VEGAN</span></div><div className="product-content"><small>{p.origin} • {p.cocoa}</small><h3>{p.name}</h3><p>{p.subtitle}</p><div className="bar"><i style={{width:`${p.reserved}%`}}/></div><div className="progress-row"><b>{p.reserved} kg / {p.goal} kg</b><span>{p.days} dní</span></div><div className="card-bottom"><div><small>od</small><strong>{money(Math.round(p.price250*.85))}</strong><del>{money(p.price250)}</del></div><button>Rezervovat</button></div></div></article>}
function Campaigns({choose}){return <main className="subpage"><div className="page-title"><span>AKTIVNÍ KAMPANĚ</span><h1>Předprodeje čokolád</h1><p>Každá rezervace nás posune blíž k výrobě nové limitované várky. Všechny aktuální čokolády jsou vegan.</p></div><div className="filter"><button className="active">Všechny</button><button>Nejblíž výrobě</button><button>Novinky</button></div><div className="cards grid">{products.map(p=><ProductCard key={p.slug} p={p} choose={choose}/>)}</div></main>}
function Detail({p,size,setSize,retail,presale,startReserve,go}){return <main className="detail"><button className="back" onClick={()=>go('campaigns')}>← Zpět na předprodeje</button><div className="detail-grid"><div className="detail-photo"><img src={p.image}/><span className="vegan">VEGAN</span></div><div className="detail-copy"><small>{p.origin} • {p.cocoa}</small><h1>{p.name}</h1><p className="detail-lead">{p.subtitle}</p><div className="campaign-progress"><div><b>{p.reserved} kg rezervováno</b><span>Cíl {p.goal} kg</span></div><div className="bar"><i style={{width:`${p.reserved}%`}}/></div><small>Do konce kampaně zbývá {p.days} dní</small></div><h3>Vyberte množství</h3><div className="size-picker">{sizes.map(s=><button key={s.g} className={size.g===s.g?'selected':''} onClick={()=>setSize(s)}><b>{s.label}</b><span>{money(p.price250*s.mult)}</span></button>)}</div><div className="summary"><div><span>Běžná cena</span><del>{money(retail)}</del></div><div><span>Předprodejní sleva 15 %</span><b>− {money(retail-presale)}</b></div><div className="total"><span>Zaplatíte nyní</span><strong>{money(presale)}</strong></div></div><button className="primary wide" onClick={startReserve}>Rezervovat za {money(presale)}</button><p className="cancel-note">↩ Rezervaci můžete kdykoliv zrušit. Peníze vrátíme bez zbytečného odkladu.</p></div></div><section className="detail-info"><article><span>CHUŤOVÝ PROFIL</span><h2>Co můžete čekat</h2><p>{p.taste}</p></article><article><span>PO VÝROBĚ</span><h2>Vyberete si způsob doručení</h2><p>Necháte si čokoládu ihned poslat, nebo si ji přidáte k větší objednávce na BioBezObalu.cz pomocí voucheru v plné hodnotě produktu.</p></article></section></main>}
function Account({user,reservations,setAuthOpen,logout}){if(!user)return <main className="empty"><h1>Váš klubový účet</h1><p>Přihlaste se a uvidíte své rezervace, vouchery i stav výroby.</p><button className="primary" onClick={()=>setAuthOpen(true)}>Přihlásit se</button></main>;return <main className="subpage account-page"><div className="account-hero"><div><span>MŮJ ÚČET</span><h1>Ahoj, {user.name.split(' ')[0]} 👋</h1><p>Tady máte všechny rezervace a jejich aktuální stav.</p></div><button className="ghost" onClick={logout}>Odhlásit se</button></div>{reservations.length===0?<div className="empty-card"><h2>Zatím tu nic není</h2><p>Po první rezervaci se tady objeví její stav, zaplacená částka a voucher.</p></div>:<div className="reservations">{reservations.map(r=><article key={r.id}><div className="res-top"><div><span className="status-dot">●</span><small>{r.status}</small><h3>{r.product}</h3><p>{r.size} • {r.delivery==='now'?'Poslat ihned po výrobě':'Přidat k další objednávce'}</p></div><b>{money(r.paid)}</b></div><div className="production"><span className="done">Rezervováno</span><i/><span>Kampaň</span><i/><span>Výroba</span><i/><span>Připraveno</span></div><div className="voucher-row"><div><small>VOUCHER PO VÝROBĚ</small><strong>{r.code}</strong><span>Hodnota {money(r.value)}</span></div><button onClick={()=>navigator.clipboard?.writeText(r.code)}>Kopírovat kód</button></div></article>)}</div>}</main>}
function Behind(){return <main className="subpage"><div className="page-title"><span>ZE ZÁKULISÍ</span><h1>Od kakaové hmoty po hotovou tabulku</h1><p>Sledujte přípravu receptur, testování i výrobu jednotlivých kampaní.</p></div><div className="behind-grid"><article className="big"><img src="/chocolate-4.jpg"/><div><small>VÝVOJ RECEPTURY</small><h2>Testujeme novou citronovou bílou čokoládu</h2><p>Hledáme poměr, který zachová čistou chuť kakaového másla a přitom nabídne výraznou svěžest.</p></div></article><article><img src="/chocolate-3.jpg"/><div><small>VÝROBA</small><h3>První zkušební várka</h3></div></article><article><img src="/chocolate-2.jpg"/><div><small>SUROVINY</small><h3>Nové kakaové máslo z Dominikánské republiky</h3></div></article></div></main>}
function AuthModal({onClose,onLogin}){const [mode,setMode]=useState('login');const [name,setName]=useState('Tomáš Marek');const [email,setEmail]=useState('tomas@example.cz');return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal auth"><button className="x" onClick={onClose}>×</button><span>BioBezObalu Club</span><h2>{mode==='login'?'Přihlášení':'Vytvořit účet'}</h2><p>V prototypu se údaje ukládají pouze do tohoto prohlížeče.</p>{mode==='register'&&<label>Jméno<input value={name} onChange={e=>setName(e.target.value)}/></label>}<label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Heslo<input type="password" defaultValue="heslo123"/></label><button className="primary wide" onClick={()=>onLogin({name:mode==='login'?'Tomáš Marek':name,email})}>{mode==='login'?'Přihlásit se':'Zaregistrovat se'}</button><button className="switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Nemáte účet? Zaregistrovat se':'Už máte účet? Přihlásit se'}</button></div></div>}
function ReserveModal({p,size,retail,presale,onClose,finish}){const [delivery,setDelivery]=useState('later');const [step,setStep]=useState(1);return <div className="overlay"><div className="modal reserve"><button className="x" onClick={onClose}>×</button>{step===1?<><span>KROK 1 ZE 2</span><h2>Jak chcete čokoládu převzít?</h2><div className="delivery-options"><button className={delivery==='now'?'selected':''} onClick={()=>setDelivery('now')}><b>📦 Poslat ihned po výrobě</b><small>Po dokončení vás vyzveme k doplacení dopravy, pokud nebude zdarma.</small></button><button className={delivery==='later'?'selected':''} onClick={()=>setDelivery('later')}><b>🛒 Přidat k větší objednávce</b><small>Dostanete voucher v plné hodnotě produktu pro použití na e-shopu.</small></button></div><button className="primary wide" onClick={()=>setStep(2)}>Pokračovat k platbě</button></>:<><span>KROK 2 ZE 2</span><h2>Souhrn rezervace</h2><div className="order-line"><div><b>{p.name}</b><small>{size.label}</small></div><b>{money(presale)}</b></div><div className="payment"><label>Číslo karty<input defaultValue="4242 4242 4242 4242"/></label><div><label>Platnost<input defaultValue="12/29"/></label><label>CVC<input defaultValue="123"/></label></div></div><div className="modal-summary"><span>Běžná hodnota produktu <b>{money(retail)}</b></span><span>Sleva předprodeje <b>−15 %</b></span><strong>K úhradě {money(presale)}</strong></div><button className="primary wide" onClick={()=>finish(delivery)}>Zaplatit a rezervovat</button><small className="demo">Demonstrační platba – nic se skutečně nestrhne.</small></>}</div></div>}
function Footer({go}){return <footer><div className="brand light"><span>BB</span><div><b>BioBezObalu</b><small>CHOCOLATE CLUB</small></div></div><p>Limitované vegan čokolády, o kterých rozhodují zákazníci.</p><div><button onClick={()=>go('campaigns')}>Předprodeje</button><button onClick={()=>go('behind')}>Ze zákulisí</button><a href="https://biobezobalu.cz">BioBezObalu.cz</a></div></footer>}
